//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.15
//
package com.xeed.cheapnsale.user;

import com.amazonaws.regions.Regions;

public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT = "Foodle";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION = Regions.fromName("ap-northeast-1");
    public static final String AMAZON_COGNITO_IDENTITY_POOL_ID =
            "ap-northeast-1:d5713885-54b3-414c-b22d-4298429ad85e";
    public static final String GOOGLE_CLIENT_ID = "680597328201-q4i4pbt9lu62m1lu17054gig987hlmre.apps.googleusercontent.com";

}
